### ISSUE TITLE
How long does it take for each image?

### ISSUE THREAD

**Issue by bolimath** [safwankdb/Deep-Image-Prior-PyTorch#1]
I am interested in the time complexity of the algorithm. How long does the algorithm take for an image (i.e. with size 256*256) ?

**Comment by safwankdb** [comment]
I haven't profiled the runs but running on google colab for a few 100 iterations takes less than 1 minute. The quality of image depends on the number of iterations the algorithm runs for.

Also, I wrote the network for 256x256 images but you'll have to change it for other sizes. The complexity wrt image size would be same as complexity of the conv layers themselves $O(n^2log(n))$
